### PR TITLE
Bump chokidar dependency for latest iojs support

### PR DESCRIPTION
**Pull request by Globegitter**
Tested on my local project.

### CODE REVIEW

**Comment by Globegitter** [comment]
@sgress454 Any chance to get this merged?

**Comment by sgress454** [comment]
Have you tested it with older versions of Node? I can't find stats anywhere, but anecdotal evidence points to a very wide range of installed versions, from v0.10.x up.  I don't want to merge a fix for io.js if it breaks things for Node!

**Comment by Globegitter** [comment]
Just testing on `0.10.36` now.

**Comment by Globegitter** [comment]
@sgress454 Yep works fine :)

**Comment by sgress454** [comment]
Good enough for me.  Thanks!

**Pull request merged**
