### PR TITLE
More specific info on dirs config option in README

### PR DESCRIPTION
**Pull request by bostrom**
As discussed in #14. 

Add more specific info about dirs configuration options and include example configuration.

### CODE REVIEW

**Comment by sgress454** [comment]
@bostrom Awesome--can you add `api/services` to the list of default folders, too? It was added in another PR.  Thanks!

**Comment by bostrom** [comment]
Done. Did I understand correctly that services are still not reloaded, only watched?

**Comment by sgress454** [comment]
No, services are one of the three things that [are reloaded](https://github.com/sgress454/sails-hook-autoreload/blob/master/index.js#L69).

**Comment by bostrom** [comment]
Doh! Adding...

**Comment by bostrom** [comment]
Better? :)

**Comment by sgress454** [comment]
Looks great, thanks!

**Pull request merged**
